[package]
name = "robanukat"
version = "0.0.1"
authors = ["Venkat Venkataraju <venkat.venkataraju@yahoo.com>", "Chuchu Ma <me@chuchuma.com>"]

[dependencies]
url = "*"
mount = "*"
router = "*"
iron = "0.4.*"
staticfile = "*"
rustc-serialize = "*"
